name: Build and Upload to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Debug environment
      working-directory: ./datamule
      run: |
        python --version
        pip --version
        echo $PATH
    
    - name: Install dependencies with verification
      working-directory: ./datamule
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine --verbose
        pip show wheel
        pip list | grep wheel
    
    - name: Build package
      working-directory: ./datamule
      run: |
        python -c "from setuptools.command.bdist_wheel import bdist_wheel; print('Wheel command is available')"
        python setup.py sdist bdist_wheel
    
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      working-directory: ./datamule
      run: |
        twine upload dist/*