name: Build and Upload to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      working-directory: ./datamule
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install twine
    
    - name: Fix wheel integration
      working-directory: ./datamule
      run: |
        # Install wheel in a way that ensures proper integration with setuptools
        pip uninstall -y wheel setuptools
        pip install setuptools==69.0.3
        pip install wheel==0.42.0
        # Verify installation
        pip list | grep wheel
        pip list | grep setuptools
    
    - name: Build package
      working-directory: ./datamule
      run: |
        python setup.py sdist bdist_wheel
    
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      working-directory: ./datamule
      run: |
        twine upload dist/*