name: Build and Upload to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
        pip install twine
    
    - name: Build wheel
      working-directory: ./datamule
      run: |
        python setup.py bdist_wheel
    
    - name: Store wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: datamule/dist/*.whl

  upload_pypi:
    needs: build_wheels
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools twine
    
    - name: Download all wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: datamule/dist
    
    - name: Build source distribution
      working-directory: ./datamule
      run: python setup.py sdist
    
    - name: Upload to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      working-directory: ./datamule
      run: twine upload dist/*