name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Debug directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Files and directories at root level:"
          ls -la
          echo "Does docs-rewrite exist?"
          test -d docs-rewrite && echo "Yes" || echo "No"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions
          # Add any additional dependencies your docs need
          # pip install -r docs-rewrite/requirements.txt

      - name: Build Documentation
        run: |
          cd docs-rewrite
          mkdocs build
          
      - name: Check Build Directory
        run: |
          pwd
          ls -la docs-rewrite/site || true
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-rewrite/site
          force_orphan: true  # This ensures a fresh history
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy MkDocs documentation [skip ci]'
          full_commit_message: |
            Deploy MkDocs documentation
            
            Build from ${{ github.sha }}
            Triggered by ${{ github.event_name }}